---
version: "3.7"

x-rpmbuild:
  channel_name: &rpmbuild_channel stable
  dist: &rpmbuild_dist .el9
  email: &rpmbuild_email foundationgeoint-packaging@maxar.com
  image_prefix: &rpmbuild_image_prefix ${IMAGE_PREFIX}
  packager_name: &rpmbuild_name FoundationGEOINT Packaging
  postgres_version: &postgres_version "15"
  vendor: &rpmbuild_vendor Maxar Technologies
  base_args: &rpmbuild_base_args
    rpmbuild_dist: *rpmbuild_dist
    rpmbuild_email: *rpmbuild_email
    rpmbuild_gid: ${RPMBUILD_GID}
    rpmbuild_name: *rpmbuild_name
    rpmbuild_uid: ${RPMBUILD_UID}
  build_defaults: &build_defaults
    context: .
    dockerfile: docker/el9/Dockerfile.rpmbuild-generic
    labels:
      maintainer: *rpmbuild_email
      vendor: *rpmbuild_vendor
  build_args_defaults: &build_args_defaults
    rpmbuild_channel: *rpmbuild_channel
    rpmbuild_image_prefix: *rpmbuild_image_prefix
    rpmbuild_image: rpmbuild
  # Configuration for building every application RPM.
  rpms:
    mod_tile:
      image: rpmbuild-mod_tile
      version: &mod_tile_version 0.6.1-3
    nominatim:
      image: rpmbuild-nominatim
      version: &nominatim_version 4.0.1-1
    nominatim-ui:
      image: rpmbuild-nominatim-ui
      version: &nominatim_ui_version 3.2.8-1
    osrm-backend:
      image: rpmbuild-osrm-backend
      version: &osrm_backend_version 5.26.0-1
    osrm-frontend:
      defines:
        git_ref: 4a9f214b4cdd35e7dff5c171e2bad549da6a2d8e
      image: rpmbuild-osrm-frontend
      version: &osrm_frontend_version 2021.9.30-1
    overpass-api:
      image: rpmbuild-overpass-api
      version: &overpass_api_version 0.7.58.5-1
    taginfo:
      defines:
        abseil_git_ref: 384a25d5e19228ceb7641676aefd58c4ca7a9568
        git_ref: f58d373b9214f1b81ca2572e78ec57ace97e18ac
        tools_git_ref: 28264e63a2b3027cec69ae4906ef689029df627b
      image: rpmbuild-taginfo
      version: &taginfo_version 2022.10.24-1
  service_volumes: &service_volumes
    - ./RPMS:/rpmbuild/RPMS:rw
    - ./SOURCES/el9:/rpmbuild/SOURCES:rw
    - ./SPECS/el9:/rpmbuild/SPECS:ro
    - ./scripts:/rpmbuild/scripts:ro
  service_defaults: &service_defaults
    command: tail -f /dev/null
    init: true
    volumes: *service_volumes

services:
  # Base images
  rpmbuild:
    build:
      context: .
      dockerfile: docker/el9/Dockerfile.rpmbuild
      args:
        <<: *rpmbuild_base_args
      labels:
        maintainer: *rpmbuild_email
        vendor: *rpmbuild_vendor
    command: tail -f /dev/null
    image: ${IMAGE_PREFIX}rpmbuild
    init: true
    user: nobody
  rpmbuild-generic:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
    image: ${IMAGE_PREFIX}rpmbuild-generic
  # RPM images
  rpmbuild-mod_tile:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_MOD_TILE_PACKAGES}
  rpmbuild-nominatim:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_NOMINATIM_PACKAGES}
        postgres_version: *postgres_version
        rpmbuild_image: rpmbuild-generic
      dockerfile: docker/el9/Dockerfile.rpmbuild-nominatim
  rpmbuild-nominatim-ui:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_NOMINATIM_UI_PACKAGES}
        rpmbuild_image: rpmbuild-generic
      dockerfile: docker/el9/Dockerfile.rpmbuild-nominatim-ui
  rpmbuild-osrm-backend:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        nodejs_version: 16
        packages: ${RPMBUILD_OSRM_BACKEND_PACKAGES}
  rpmbuild-osrm-frontend:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OSRM_FRONTEND_PACKAGES}
  rpmbuild-overpass-api:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_OVERPASS_API_PACKAGES}
  rpmbuild-taginfo:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: ${RPMBUILD_TAGINFO_PACKAGES}
