---
version: '3.7'

x-rpmbuild:
  channel_name: &rpmbuild_channel stable
  dist: &rpmbuild_dist .el7
  email: &rpmbuild_email foundationgeoint-packaging@maxar.com
  image_prefix: &rpmbuild_image_prefix ${IMAGE_PREFIX}
  packager_name: &rpmbuild_name 'FoundationGEOINT Packaging'
  postgres_version: &postgres_version '13'
  vendor: &rpmbuild_vendor 'Maxar Technologies'
  base_args: &rpmbuild_base_args
    rpmbuild_dist: *rpmbuild_dist
    rpmbuild_email: *rpmbuild_email
    rpmbuild_name: *rpmbuild_name
    rpmbuild_uid: "${RPMBUILD_UID}"
    rpmbuild_gid: "${RPMBUILD_GID}"
  build_defaults: &build_defaults
    context: .
    dockerfile: docker/Dockerfile.rpmbuild-generic
    labels:
      maintainer: *rpmbuild_email
      vendor: *rpmbuild_vendor
  build_args_defaults: &build_args_defaults
    rpmbuild_channel: *rpmbuild_channel
    rpmbuild_image_prefix: *rpmbuild_image_prefix
    rpmbuild_image: rpmbuild-generic
  # Use consistent values for minimum versions for RPM build
  # and runtime requirements.
  minimum_versions:
    geos: &geos_min_version '3.9.0'
    gdal: &gdal_min_version '3.2.0'
    libosmium: &libosmium_min_version '2.16.0'
    postgis_min_version: &postgis_min_version '3.1.0'
    proj: &proj_min_version '7.2.0'
    protobuf: &protobuf_min_version '3.0.0'
    protobuf-c: &protobuf_c_min_version '1.3.0'
    protozero: &protozero_min_version '1.7.0'
    sqlite_min_version: &sqlite_min_version '3.11.0'
  # Configuration for building every application RPM.
  rpms:
    nominatim:
      image: rpmbuild-nominatim
      version: &nominatim_version '4.0.1-1'
    nominatim-ui:
      image: rpmbuild-nominatim-ui
      version: &nominatim_ui_version '3.2.4-1'
    osrm-backend:
      image: rpmbuild-osrm-backend
      version: &osrm_backend_version '5.26.0-1'
    osrm-frontend:
      defines:
        commit: 4a9f214b4cdd35e7dff5c171e2bad549da6a2d8e
      image: rpmbuild-osrm-frontend
      version: &osrm_frontend_version '2021.9.30-1'
    overpass-api:
      image: rpmbuild-overpass-api
      version: &overpass_api_version '0.7.56.9-2'
    taginfo:
      defines:
        abseil_commit: 0f3bb466b868b523cf1dc9b2aaaed65c77b28862
        commit: bc64c07b71455f22310fc3ec7123b58150ae1b2b
        tools_commit: 52888a81d56e090f7e3b89c99342989ae476bb31
      image: rpmbuild-taginfo
      version: &taginfo_version '2021.7.7-1'
  service_volumes: &service_volumes
    - "./RPMS:/rpmbuild/RPMS:rw"
    - "./SOURCES:/rpmbuild/SOURCES:rw"
    - "./SPECS:/rpmbuild/SPECS:ro"
    - "./scripts:/rpmbuild/scripts:ro"
  service_defaults: &service_defaults
    command: 'tail -f /dev/null'
    init: true
    volumes: *service_volumes

services:
  rpmbuild:
    build:
      context: .
      dockerfile: docker/Dockerfile.rpmbuild
      args:
        <<: *rpmbuild_base_args
      labels:
        maintainer: *rpmbuild_email
        vendor: *rpmbuild_vendor
    command: 'tail -f /dev/null'
    image: ${IMAGE_PREFIX}rpmbuild
    init: true
    user: nobody
  rpmbuild-generic:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        rpmbuild_image: rpmbuild
    image: ${IMAGE_PREFIX}rpmbuild-generic
  rpmbuild-generic-geoint-deps:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
      dockerfile: docker/Dockerfile.rpmbuild-generic-geoint-deps
    image: ${IMAGE_PREFIX}rpmbuild-generic-geoint-deps
  rpmbuild-generic-nodejs:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
      dockerfile: docker/Dockerfile.rpmbuild-generic-nodejs
    image: ${IMAGE_PREFIX}rpmbuild-generic-nodejs
  rpmbuild-nominatim:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: "${RPMBUILD_NOMINATIM_PACKAGES}"
        postgres_version: *postgres_version
        rpmbuild_image: rpmbuild-generic-geoint-deps
      dockerfile: docker/Dockerfile.rpmbuild-nominatim
  rpmbuild-nominatim-ui:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: "${RPMBUILD_NOMINATIM_UI_PACKAGES}"
        rpmbuild_image: rpmbuild-generic-nodejs
      dockerfile: docker/Dockerfile.rpmbuild-generic-nodejs
  rpmbuild-osrm-backend:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: "${RPMBUILD_OSRM_BACKEND_PACKAGES}"
        rpmbuild_image: rpmbuild-generic-geoint-deps
      dockerfile: docker/Dockerfile.rpmbuild-generic-nodejs
  rpmbuild-osrm-frontend:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: "${RPMBUILD_OSRM_FRONTEND_PACKAGES}"
        rpmbuild_image: rpmbuild-generic-nodejs
      dockerfile: docker/Dockerfile.rpmbuild-generic-nodejs
  rpmbuild-overpass-api:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: "${RPMBUILD_OVERPASS_API_PACKAGES}"
        rpmbuild_image: rpmbuild
      dockerfile: docker/Dockerfile.rpmbuild-generic
  rpmbuild-taginfo:
    <<: *service_defaults
    build:
      <<: *build_defaults
      args:
        <<: *build_args_defaults
        packages: "${RPMBUILD_TAGINFO_PACKAGES}"
        rpmbuild_image: rpmbuild-generic-geoint-deps
      dockerfile: docker/Dockerfile.rpmbuild-generic-geoint-deps
