ARG rpmbuild_channel
ARG rpmbuild_image=rpmbuild-generic
ARG rpmbuild_image_prefix
# hadolint ignore=DL3007
FROM ${rpmbuild_image_prefix}${rpmbuild_image}:latest

ARG packages=""

# Temporarily switch to root for package installation.
USER root

# If any package dependencies are needed, install them.
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
# hadolint ignore=DL3033
RUN --mount=type=cache,target=/var/cache/yum \
    /usr/local/bin/nodesource-repo.sh && \
    /usr/local/bin/yarn-repo.sh && \
    if [ -n "${packages}" ]; then yum -q -y install ${packages} && yum -q -y clean all; fi

# Use unprivileged RPM build user and work directory by default.
USER ${RPMBUILD_USER}
WORKDIR ${RPMBUILD_HOME}
