---
name: Build & Push (EL9)

on:
  push:
    paths:
      - .dockerignore
      - .github/workflows/ci.el9.yml
      - Makefile.el9
      - SOURCES/el9/**
      - SPECS/el9/**
      - docker-compose.el9.yml
      - docker/el9/**
      - scripts/**

env:
  DOCKER_BUILDKIT: 1
  EL_VERSION: el9

jobs:
  build-images:
    name: Build `${{ matrix.image }}` Image
    runs-on: ubuntu-latest

    strategy:
      # Uncomment the following lines in order to build & push base images
      max-parallel: 1
      matrix:
        image:
          - rpmbuild
          - rpmbuild-generic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old images
        uses: radiant-maxar/geoint-actions/github-api/delete-package@v1.2
        with:
          el_version: ${{ env.EL_VERSION }}
          package_name: ${{ matrix.image }}
          token: ${{ secrets.PKG_DELETE_TOKEN }}
          token_type: token

      - name: Build `${{ matrix.image }}` Image
        uses: radiant-maxar/geoint-actions/build@v1.2
        with:
          el_version: ${{ env.EL_VERSION }}
          make_target: ${{ matrix.image }}
          push_image: true
          upload_rpms: false


  build-rpms:
    name: Build `${{ matrix.rpm }}` RPM(s)
    needs: build-images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rpm:
          - geonode
          - mapproxy
          - mod_tile
          - nominatim
          - nominatim-ui
          - osrm-backend
          - osrm-frontend
          - overpass-api
          - taginfo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build `${{ matrix.rpm }}` RPM(s)
        uses: radiant-maxar/geoint-actions/build@v1.2
        with:
          el_version: ${{ env.EL_VERSION }}
          make_target: ${{ matrix.rpm }}


  create-and-push-repo:
    name: Create & push repository
    if: ${{ github.ref_name != 'stable' }}
    needs: build-rpms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download RPMS artifact
        uses: radiant-maxar/geoint-actions/artifact/download@v1.2
        with:
          base_path: .
          directory: RPMS
          el_version: ${{ env.EL_VERSION }}

      - name: Create repository
        uses: radiant-maxar/geoint-actions/repository/create@v1.2
        with:
          el_version: ${{ env.EL_VERSION }}
          repo_dirname: non-stable/${{ github.ref_name }}

      - name: Upload repository
        uses: radiant-maxar/geoint-actions/repository/upload@v1.2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          el_version: ${{ env.EL_VERSION }}
          repo_dirname: non-stable/${{ github.ref_name }}
          s3_bucket: geoint-apps
